export { default as Arrow } from './Arrow.svg'
export { default as ArrowCurved } from './ArrowCurved.svg'
export { default as Sign } from './Sign.svg'
export { default as MenuIcon } from './Menuopen.svg'
export { default as CloseIcon } from './CloseIcon.svg'